export type Perk = { id:string; label:string; title:string; description:string; value:string; x:number; y:number; mobileX:number; mobileY:number };
export type Tier = { id:string; code:string; name:string; spend:string; tagline:string; headline:string; points:number; birthday:number; perks:Perk[]; benefits:string[] };
const sales = 'Early access to sales';
const collection = 'Early access to collection launches';
const welcome=(x=22,y=27,mobileX=17,mobileY=24):Perk=>({id:'welcome',label:'Your room key',title:'A little something on arrival.',description:'Create an account and begin your Heartbreak Hotel stay with 40 welcome points.',value:'40 welcome points',x,y,mobileX,mobileY});
const birthday=(value:number,x:number,y:number,mobileX:number,mobileY:number):Perk=>({id:'birthday',label:'Birthday treat',title:'Make an entrance. It’s your birthday.',description:`Tell us your birthday and enjoy a ${value}% birthday voucher. Your birthday look is calling.`,value:`${value}% birthday voucher`,x,y,mobileX,mobileY});
const firstAccess=(x:number,y:number,mobileX:number,mobileY:number):Perk=>({id:'sales',label:'First access',title:'First through the doors.',description:'Get early access to sales. More time to find the pieces you’ve had your eye on.',value:sales,x,y,mobileX,mobileY});
const launches=(x:number,y:number,mobileX:number,mobileY:number):Perk=>({id:'launches',label:'New collection access',title:'On the list. Ahead of the rest.',description:'Get early access to collection launches, before the doors open to everyone else.',value:collection,x,y,mobileX,mobileY});
const earning=(rate:number,x:number,y:number,mobileX:number,mobileY:number):Perk=>({id:'points',label:`${rate}× the points`,title:'Your wardrobe has its rewards.',description:`Earn ${rate} points for every $1 spent. Turn your points into money off a future order.`,value:`${rate} points per $1 spent`,x,y,mobileX,mobileY});
export const tiers:Tier[]=[
 {id:'suite',code:'01',name:'Suite',spend:'$0–$299',tagline:'Your first taste of the good life.',headline:'EVERY GREAT NIGHT\nSTARTS SOMEWHERE.',points:1,birthday:10,perks:[welcome(44.5,53,44.5,49),birthday(10,89.8,64,91,53.5),firstAccess(34.5,85,32,64)],benefits:['40 welcome points','1 point per $1 spent','10% birthday voucher',sales]},
 {id:'deluxe',code:'02',name:'Deluxe Suite',spend:'$300–$599',tagline:'A bigger birthday treat. First access to new collections.',headline:'CONSIDER THIS\nYOUR UPGRADE.',points:1,birthday:15,perks:[welcome(87,77,16,63.5),launches(81,42,70,40),birthday(15,68,55,90,47),firstAccess(58,77,43,61)],benefits:['40 welcome points','1 point per $1 spent','15% birthday voucher',sales,collection]},
 {id:'presidential',code:'03',name:'Presidential Suite',spend:'$600–$1,999',tagline:'Double the points. Raise your expectations.',headline:'GOOD TASTE.\nGREAT PRIVILEGES.',points:2,birthday:15,perks:[earning(2,29,56,13,54),launches(87,46,50,49),birthday(15,73,70,84,67)],benefits:['40 welcome points','2 points per $1 spent','15% birthday voucher',sales,collection]},
 {id:'penthouse',code:'PH',name:'Penthouse Suite',spend:'$2,000+',tagline:'The highest floor. The inside list.',headline:'THE NIGHT\nIS YOURS.',points:3,birthday:20,perks:[{id:'events',label:'Exclusive events',title:'Your name is on the list.',description:'Invites to exclusive events and experiences. Welcome to the Heartbreak Hotel inner circle.',value:'Exclusive events & experiences',x:60,y:87,mobileX:70,mobileY:70}, {id:'concierge',label:'Heartbreak Concierge',title:'Consider it taken care of.',description:'Priority customer care from Heartbreak Concierge. A little extra attention, just for you.',value:'Priority customer care',x:89,y:66,mobileX:94,mobileY:60},earning(3,14,56,8,52),birthday(20,45.5,72,44,62),launches(39,49,32,49)],benefits:['Surprise welcome points','3 points per $1 spent','20% birthday voucher',sales,collection,'Invites to exclusive events and experiences','Priority customer care from Heartbreak Concierge']}
];
export const earn=[['Create an account','40 points'],['Every $1 spent','1 point at Suite & Deluxe'],['Sign up for SMS','30 points'],['Download the Outcast App','30 points'],['Tell us your birthday','Birthday voucher'],['Follow on Instagram','10 points'],['Follow on TikTok','10 points'],['Leave a review','Up to 60 points']];

export const mobileCropTop = [160, 140, 80, 190];
export const mobileY = (floor:number, y:number) => (y * 12.64 - mobileCropTop[floor]) / (1264 - mobileCropTop[floor]) * 100;
